name: RELEASE
on: [workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm i
      - name: Lint
        run: npx nx run foo:lint
      - name: Test
        run: npx nx run foo:test --configuration=ci
      - name: Release
        run: npx nx  run foo:semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
